### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by xCroffx** [wanjizheng/iBarter_WPF#1] opened 2024-05-08 13:45 UTC
I run it as Admin but keep getting an error at bottom.

https://imgur.com/FD8JiWR

and the other window i get this  "https://imgur.com/FD8JiWR"

https://imgur.com/x3Ti6dN

So I found a guide to register every dll on my pc through admin command prompt and it didnt work.

Im in my 50's and worked construction my whole life so im not very pc savvy

**Comment by wanjizheng** [comment] 2024-05-09 12:31
Hi xCroffx, thanks for reporting this issue. Since you figured out how to report issues on GitHub correctly, I'd say your PC skill is good :D

You don't need to register dlls via command prompt, the required dll will be registered automatically when you start the application. Please could you let me know your windows version? (e.g. is it Windows 10 or 11?) Moreover, which version of iBarter are you using? Is it beta 3?

**Comment by xCroffx** [comment] 2024-05-10 00:16
Windows 11 version 23h2  build 22631.3527

Reinstalled windows last night and tried it, nothing changed, then did an inplace upgrade/install and still nothing.

I tried 2beta and 3beta

**Comment by xCroffx** [comment] 2024-05-10 03:57
Well my brother has been in computer programing for about 25 years now, he remoted into my PC and did alot of debloating and optimizing stuff for me for BDO. I mentioned the problem to him and its now almost working. Not sure what he did, but its loading now. It's just not scanning.

I will ask him to fix that this weekend if he has time.

Thanks for replying, but I will first see if he can figure out when nothing happens when i hit scan now with barter window open

**Comment by wanjizheng** [comment] 2024-05-12 05:11
It might be the case that the anti-virus software deleted the PureDM.dll file in the application folder. Double-check the application folder and make sure you have that dll file there.

**Comment by Medo974** [comment] 2024-05-14 03:43
I have the same problem but I'm running Win10 Build 19045, I have the loading image with Beta3 and then nothing. I tried Beta2, it finishes loading but crashes after 2 or 3 sec without being able to do anything and I have no error code. I've checked several times that all the files are present, I've also tested without antivirus but it's not coming from there.

**Comment by wanjizheng** [comment] 2024-05-20 20:40
Will need to do more tests, but I can't reproduce this kind of error on my machines.

**Comment by 2bklag** [comment] 2024-05-25 00:10
I have had the same issue. 
I had unpacked the .zip into an iBarter3 folder in the game directory under D:\Games\BDO\iBarter3.
Here is what i have done to fix it:

- deleted the iBarter3 folder from BDO game folder.
- redownloaded the .zip
- created a new folder on my system drive under C:\Programs\iBarter3
- COPIED all files from the .zip into the folder. NOT unzipped it (i dont know why, bit this way it worked)
- Checked "run as admin" in the configuration from the iBarter.exe 
- still started the .exe via rightclick -> run as admin.
- (.Net was already installed from last time)

**Comment by pdmostert** [comment] 2024-06-22 13:49
I am having a similar issue. The above steps did not resolve the issue. I do however have Visual Studio installed and ran the application in debug mode, I do get an error when trying to initialize the  PureDM. It failed on line 124 of MainWindow.xaml.cs with an error that the .dll does not exist. I fixed this by editing the properties to "copy if newer". Now it find the dll, but fails on authentication. I assume the credentials that you use to new PureDM is not active anymore.

**Comment by pdmostert** [comment] 2024-06-22 14:14
I am having a similar issue. The above steps did not resolve the issue. I do however have Visual Studio installed and ran the application in debug mode, I do get an error when trying to initialize the  PureDM. It failed on line 124 of MainWindow.xaml.cs with an error that the .dll does not exist. I fixed this by editing the properties to "copy if newer". Now it find the dll, but fails on authentication. I assume the crenditials that you use to new PureDM is not active anymore.

**Comment by pdmostert** [comment] 2024-06-22 14:14
![mmc_SMBmtK7SQX](https://github.com/wanjizheng/iBarter_WPF/assets/16480410/6e6b4d3b-852f-45b5-97fd-b5e5583de7e6)

**Comment by wanjizheng** [comment] 2024-07-15 14:09
If you debug the code, make sure you run the Visual Studio as admin. Moreover, change the configuration manager to x86 instead of  AnyCPU, as the PureDM.dll only works under x86.

Finally, ensure you white-list the PureDM.dll file in your anti-virus software.

**Comment by wanjizheng** [comment] 2024-08-19 16:16
#3 
The compatibility issue has been fixed in the Beta 4.0 version.

**Closed by wanjizheng** 2024-08-19 16:16 UTC
